security:
  enable_authenticator_manager: true

  providers:
    main:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      logout: ~
      custom_authenticators:
        - App\Security\TwitchAuthenticator

  access_control:
    - { path: ^/_wdt/.*, roles: PUBLIC_ACCESS }
    - { path: ^/_profiler/.*, roles: PUBLIC_ACCESS }
